Traducción capitulo4
JaquerEspeis/inventar-con-python pull request #11
Opened 2018-04-24 22:47 UTC by dtec83

Traducción capitulo4.md

2018-04-25 05:13 UTC, come-maiz requested changes
¡Gracias @dtec83! Dejé comentarios para mejorar la consistencia, muy pocos son correcciones.

pura vida.

2018-04-25 05:13 UTC, come-maiz commented on capitulo4.md
> +# 4 Un programa de Chistes
Un programa que cuenta chistes

2018-04-25 05:13 UTC, come-maiz commented on capitulo4.md
> +Este capítulo le cuenta algunas bromas a las personas usuarias y les demuestra algunas maneras avanzadas de utilizar cadenas utilizando la función print(). La mayoría de los juegos en este libro tend
algunas bromas -> algunos chistes
cadenas -> cadenas de caracteres
utilizar -> usar
utilizando la función -> con la función
print() -> `print()` (con backticks)
digitada -> escrita
utilizando el teclado -> usando el teclado
desplegado -> mostrado.

2018-04-25 05:13 UTC, come-maiz commented on capitulo4.md
> +* Uso de comillas simples y dobles para manejo de cadenas
cadenas de caracteres.

2018-04-25 05:13 UTC, come-maiz commented on capitulo4.md
> +* Utilizando el argumento palabra clave "end" de la función print() para evitar nuevas lineas
Utilizando el -> uso del
creo que podríamos traducir «keyword parameter» como «parametro nombrado».
En español, las primeras comillas son « y ». Entonces "end" -> «end»
print() -> `print()`

2018-04-25 05:13 UTC, come-maiz commented on capitulo4.md
> +Ya aprendiste cómo desplegar una salida de texto simple utilizando la función print(). Ahora vamos a profundizar y veremos cómo las cadenas y `print()` funcionan en Python.
aprendiste -> aprendió. La primera traducción debería ser lo más neutral posible, usando usted. Después se puede ajustar a un uso más común por región, con voseo o tuteo.
desplegar -> mostrar
utilizando -> usando
print() -> `print()`
cadenas -> cadenas de caracteres.

2018-04-25 05:13 UTC, come-maiz commented on capitulo4.md
> +## Ejemplo de ejecución del programa Chistes
Ejecución de ejemplo de Chistes

2018-04-25 05:13 UTC, come-maiz commented on capitulo4.md
> +¡Un monopatín!
lol

2018-04-25 05:13 UTC, come-maiz commented on capitulo4.md
> +
esta línea en blanco no está en el original, mejor quitarla.

2018-04-25 05:13 UTC, come-maiz commented on capitulo4.md
> +¡Porque caminando tardarían muchísimo!
:man_facepalming:

2018-04-25 05:13 UTC, come-maiz commented on capitulo4.md
> +
quitar esta línea

2018-04-25 05:13 UTC, come-maiz commented on capitulo4.md
> +Si obtienes errores después de escribir este código, compáralo con el código del libro con la herramienta diff en línea en http://invpy.com/es/diff/chistes.
Si obtiene errores después de escribir este código, compare el código que escribió con el código del libro en la herramienta de diff en línea en https://www.nostarch.com/inventwithpython#diff.

2018-04-25 05:13 UTC, come-maiz commented on capitulo4.md
> +Si obtienes errores después de escribir este código, compáralo con el código del libro con la herramienta diff en línea en http://invpy.com/es/diff/chistes.
Este párrafo va después del dibujo del pingüino.

2018-04-25 05:13 UTC, come-maiz commented on capitulo4.md
> +</pre>
Este párrafo no está en el original, mejor quitarlo.

2018-04-25 05:13 UTC, come-maiz commented on capitulo4.md
> +
Falta el título Source code for jokes. y el párrafo donde dice Open a new file editor...

2018-04-25 05:13 UTC, come-maiz commented on capitulo4.md
> +<b>chistes.py</b>
El formato de esto es más bien como:

*jokes.py*
***
<pre>
[código]
</pre>
***

Aún no se si deberíamos traducir todo el código. Yo por ahora, dejaría los nombres de archivos, variables y funciones en inglés, y traduciría solo los strings. O sea, en lugar de chistes.py lo dejaría jokes.py/ Pero esto es más por mi OCD que por una buena razón.

2018-04-25 05:13 UTC, come-maiz commented on capitulo4.md
> +<pre>
faltan los *** antes del `<pre>` y después del `</pre>`

2018-04-25 05:13 UTC, come-maiz commented on capitulo4.md
> +Las líneas de la 1 a la 3 tienen llamadas a la función `print()` que se utiliza para preguntar y responder al chiste. No se quiere que la jugadora lea de inmediato la respuesta del chiste, por lo que
usan la llamada a función `print()` para preguntar y responder al primer chiste.
jugadora > usuaria
se utiliza -> hay
De esta manera la jugadora [...] -> La usuaria leerá la primera línea del chiste, presionará ENTER, y luego leerá la respuesta.

2018-04-25 05:13 UTC, come-maiz commented on capitulo4.md
> +La persona usuaria podría escribir una cadena y pulsar INTRO, pero esa cadena no estará siendo almacenada en ninguna variable. El programa tan solo la olvidará y se moverá a la siguiente línea de cód
cadena de caracteres (x2)
pulsar -> presionar

2018-04-25 05:13 UTC, come-maiz commented on capitulo4.md
> +La última llamada a la función `print()` no tiene argumento de cadena. Esto le indica al programa que solamente despliegue una línea en blanco. Las líneas en blanco pueden ser útiles para evitar que
cadena de caracteres.

2018-04-25 05:13 UTC, come-maiz commented on capitulo4.md
> +La última llamada a la función `print()` no tiene argumento de cadena. Esto le indica al programa que solamente despliegue una línea en blanco. Las líneas en blanco pueden ser útiles para evitar que
solamente -> sólo
despliegue -> imprima
pueden ser -> son

2018-04-25 05:13 UTC, come-maiz commented on capitulo4.md
> +<pre>
***

2018-04-25 05:13 UTC, come-maiz commented on capitulo4.md
> +
***

2018-04-25 05:13 UTC, come-maiz commented on capitulo4.md
> +En la línea 5 hay una barra invertida justo antes de la comilla simple (note que es una barra invertida y no una barra inclinada). Esta barra invertida indica que la letra que se encuentra justo desp
note que `\` es una barra invertida y que `/` es una barra inclinada.
caracter -> carácter (x2)
el primer «caracter de escape» va sin énfasis, el segundo va con cursiva, no con negrita: *caracter de escape*
te -> le
ingresar al -> escribir en el 
una comilla simple -> la comilla simple

2018-04-25 05:13 UTC, come-maiz commented on capitulo4.md
> +En este caso el caracter de escape es un signo de pregunta. Si este caso, si no se incluía la barra invertida, en `¿Porqué` el signo de pregunta hubiera sido mal interpretado y habría generado un err
Esto está raro. Sugiero:
En este caso, si no incluimos la barra invertida, la comilla simple en `pa\'l` se hubiera interpretado como el final de la cadena de caracteres. Pero esta comilla necesita ser *parte de* la cadena de caracteres. La comilla simple con escape le indica a Python que debe incluir la comilla simple en la cadena de caracteres.

2018-04-25 05:13 UTC, come-maiz commented on capitulo4.md
> +Ahora, ¿cómo se podría imprimir una barra invertida?. Si se ejecuta la siguiente línea de código desde una terminal, no funcionaría:
imprimir -> mostrar
Quitar el punto al final de esa pregunta.
Agregar una nueva línea después de la pregunta.
Vaya de su programa *jokes.py* hacia la consola interactiva y escriba esta sentancia `print()`.

2018-04-25 05:13 UTC, come-maiz commented on capitulo4.md
> +>>> print('Él se fue volando en un helicóptero verde\turquesa.')
Él se fue -> Ellas se fueron
Este print debería ir en negrita:
`**print('Ellas se fueron volando en un helicóptero verde\turquesa.')**`

2018-04-25 05:13 UTC, come-maiz commented on capitulo4.md
> +Él se fue volando en un helicóptero verde    urquesa.
Ellas se fueron

2018-04-25 05:13 UTC, come-maiz commented on capitulo4.md
> +Esto es porque la "t" en "turquesa" fue vista como un **caracter de escape** debido a que estaba después de una barra invertida. El caracter de escape `t` simula la pulsación de la tecla TAB de tu te
Esta instrucción no imprimió la barra invertida porque la `t` en `turquesa` fue interpretada como un carácter de escape.
sin negrita.
caracter -> carácter
`t` -> `\t`
la pulsación de -> presionar
de tu -> del
Quitar «Hay caracteres ... escribir», que no está en el original.

2018-04-25 05:13 UTC, come-maiz commented on capitulo4.md
> +En lugar de eso, prueba con esta línea:
Esta línea le dará la salida correcta

2018-04-25 05:13 UTC, come-maiz commented on capitulo4.md
> +<pre>
***

2018-04-25 05:13 UTC, come-maiz commented on capitulo4.md
> +</pre>
***

2018-04-25 05:13 UTC, come-maiz commented on capitulo4.md
> +<pre>
***

2018-04-25 05:13 UTC, come-maiz commented on capitulo4.md
> +</pre>
***

2018-04-25 05:13 UTC, come-maiz commented on capitulo4.md
> +<pre>
`***`

2018-04-25 05:13 UTC, come-maiz commented on capitulo4.md
> +>>> print('Él se fue volando en un helicóptero verde\\turquesa.')
negrita
Ellas se fueron (x2)

2018-04-25 05:13 UTC, come-maiz commented on capitulo4.md
> +De esta manera el `\\` es un caracter de barra invertida en lugar de un `\t` que es interpretado por Python como un TAB.
carácter
en lugar de [...] -> y no hay un `\t` que interpretar como TAB

2018-04-25 05:13 UTC, come-maiz commented on capitulo4.md
> +La tabla **4-1** podremos encontrar una lista de caracteres de escape en Python.
4-1 sin negrita
podremos encontrar -> es
caracteres de escape -> algunos caracteres de escape.
Falta: , incluyendo `\n`, que es el carácter de escape de nueva línea que ha usado antes.

2018-04-25 05:13 UTC, come-maiz commented on capitulo4.md
> +|Caracter de Escape | Lo Que Imprime |
Caracter de escape
Lo que imprime

2018-04-25 05:13 UTC, come-maiz commented on capitulo4.md
> +| `\n`     | Salto de línea       |
salto de -> nueva

2018-04-25 05:13 UTC, come-maiz commented on capitulo4.md
> +Mientras todavía estamos en una terminal interactiva, veamos un poco más a fondo a las comillas. Las cadenas no siempre tienen que estar entre comillas simples en Python. También se pueden poner entr
terminal -> consola
cadenas -> cadenas de caracteres

2018-04-25 05:13 UTC, come-maiz commented on capitulo4.md
> +Mientras todavía estamos en una terminal interactiva, veamos un poco más a fondo a las comillas. Las cadenas no siempre tienen que estar entre comillas simples en Python. También se pueden poner entr
a continuación van a imprimir -> imprimen

2018-04-25 05:13 UTC, come-maiz commented on capitulo4.md
> +<pre>
`***`

2018-04-25 05:13 UTC, come-maiz commented on capitulo4.md
> +>>> print('Hola Mundo')
negrita

2018-04-25 05:13 UTC, come-maiz commented on capitulo4.md
> +>>> print("Hola Mundo")
negrita

2018-04-25 05:13 UTC, come-maiz commented on capitulo4.md
> +</pre>
`***`

2018-04-25 05:13 UTC, come-maiz commented on capitulo4.md
> +Pero no se pueden mezclar las comillas simples con las dobles. Esta siguiente línea va a retornar un error porque utiliza ambas comillas al mismo tiempo:
va a retornar -> le dará

2018-04-25 05:13 UTC, come-maiz commented on capitulo4.md
> +<pre>
`***`

2018-04-25 05:13 UTC, come-maiz commented on capitulo4.md
> +>>> print('Hola mundo")
negrita

2018-04-25 05:13 UTC, come-maiz commented on capitulo4.md
> +</pre>
`***`

2018-04-25 05:13 UTC, come-maiz commented on capitulo4.md
> +Personalmente prefiero utilizar comillas simples para no tener que mantener presionada la tecla SHIFT para escribirlas. Son mucho más fáciles de escribir y a Python no le importa cuál de las dos util
mucho más -> más
utilicemos -> usemos

2018-04-25 05:13 UTC, come-maiz commented on capitulo4.md
> +Tenga en cuenta que al igual que necesita la barra invertida (`\'`), para tener una comilla simple en una cadena encerrada entre comillas simples, también va a necesitar la barra invertida (`\"`) par
Tenga en cuenta -> También note
la barra invertida (`\'`), -> `\'`
cadena de caracteres (x2)
la barra invertida (`\"`) -> `\"`
Veamos este ejemplo

2018-04-25 05:13 UTC, come-maiz commented on capitulo4.md
> +<pre>
`***`

2018-04-25 05:13 UTC, come-maiz commented on capitulo4.md
> +>>> print('Le pedí prestado el carro a Pedro pa\'ir al pueblo. Él dijo, "Seguro."')
negrita.

2018-04-25 05:13 UTC, come-maiz commented on capitulo4.md
> +>>> print("Él dijo, \"No puedo creer que lo dejaste llevarse el carro pa'l pueblo\"")
Esta va abajo del próximo párrafo.
Él -> Ella

2018-04-25 05:13 UTC, come-maiz commented on capitulo4.md
> +En las cadenas de comillas simples no necesitas escapar las comillas dobles, y en las cadenas de comillas dobles no necesitas escapar las comillas simples. El intérprete de Python tiene inteligencia
Este párrafo no es la traducción del original.

2018-04-25 05:13 UTC, come-maiz commented on capitulo4.md
> +## El parámetro de palabra clave `end` de la función print()
En los títulos no estamos usando backticks.
el parámetro nombrado

2018-04-25 05:13 UTC, come-maiz commented on capitulo4.md
> +Ahora regresemos al archivo chistes.py y observemos las líneas de la 9 a las 6:
observemos -> veamos

2018-04-25 05:13 UTC, come-maiz commented on capitulo4.md
> +<pre>
`***`

2018-04-25 05:13 UTC, elopio commented on capitulo4.md
> +¿Te diste cuenta del segundo parámetro en el print de la línea 15?. Normalmente, `print()` añade un salto de línea al final de la cadena que imprime. Por esta razón, una función `print()` en blanco t
Te diste cuenta del -> Notó el
en el print -> en la función `print()`
un salto de -> una nueva
cadena -> cadena de caracteres
tiene la opción de un segundo parámetro: `end` (fin en inglés).

2018-04-25 05:13 UTC, elopio commented on capitulo4.md
> +Recordemos que un argumento es un valor que se le pasa a una llamada de función. La cadena en blanco qus se le pasa a la función `print()` se llama **argumento** de palabra clave. El `end` que se enc
Recordemos -> Recuerde
llamada de función -> llamada a función.
cadena -> cadena de caracteres
qus -> que
**argumento** de palabra clave -> *argumento nombrado*
**parámetro** de palabra clave -> *parámetro nombrado*.
digitar la palabra -> escribir
al antes del argumento -> antes de este

2018-04-25 05:13 UTC, elopio commented on capitulo4.md
> +<pre>
`***`

2018-04-25 05:13 UTC, elopio commented on capitulo4.md
> +</pre>
`***`

2018-04-25 05:13 UTC, elopio commented on capitulo4.md
> +Pasando una cadena en blanco usando `end`, la función `print()` no añadirá un salto de linea al final de la cadena, en lugar de esto añadirá una cadena en blanco. Por esta razón ' -Bien, gracias.' ap
un salto de -> una nueva
cadena -> cadena de caracteres.
backticks en Bien gracias
sobre -> en
No hubo salto de -> No hubo una nueva
después de que fue imprimida la cadena de caracteres `'¿Y la familia?'`.

2018-04-25 05:13 UTC, elopio commented on capitulo4.md
> +Este capítulo explora las diferentes formas en las que se puede utilizar la función `print()`. Los caracteres de escape se utilizan para los caracteres que son difíciles o imposibles de introducir al
utilizar -> usar (x3)
utilizan -> usan
introducir al -> escribir en el 
cadena -> cadena de caracteres
un salto de -> una nueva
deberás -> deberá

2018-04-25 05:13 UTC, elopio commented on capitulo4.md
> +La función `print()` añade automáticamente un carácter de salto de línea al final de la cadena que se pasa para imprimr en pantalla. La mayor parte del tiempo, es un atajo útil. Pero a veces no quier
salto de -> nueva (x2)
cadena -> cadena de caracteres (x2)
puedes -> puede
de palabra clave -> nombrado
“spam” -> `spam`“spam”
podrías -> pordía

2018-04-25 05:13 UTC, elopio commented on capitulo4.md
> +Al añadir este nivel de control sobre el texto que mostraremos en la pantalla, puedes tener formas más flexibles para hacerlo.
Este párrafo no está en el original, mejor quitarlo.

2018-04-25 21:25 UTC, dtec83 commented on capitulo4.md
> +# 4 Un programa de Chistes
listo

2018-04-25 21:25 UTC, dtec83 commented on capitulo4.md
> +Este capítulo le cuenta algunas bromas a las personas usuarias y les demuestra algunas maneras avanzadas de utilizar cadenas utilizando la función print(). La mayoría de los juegos en este libro tend
listo

2018-04-25 21:25 UTC, dtec83 commented on capitulo4.md
> +* Uso de comillas simples y dobles para manejo de cadenas
listo

2018-04-25 21:27 UTC, dtec83 commented on capitulo4.md
> +* Utilizando el argumento palabra clave "end" de la función print() para evitar nuevas lineas
keyword = palabra clave. Decir nombrado cambia demasiado el término.. yo mismo no entendería que se habla de un keyword usando esa palabra. He leído palabra clave para keyword en bastantes partes. Voto por dejarlo así, se usa en varias partes del capítulo y fijo del doc. Me avisas.

El resto fixed.

2018-04-25 21:30 UTC, dtec83 commented on capitulo4.md
> +Ya aprendiste cómo desplegar una salida de texto simple utilizando la función print(). Ahora vamos a profundizar y veremos cómo las cadenas y `print()` funcionan en Python.
listo

2018-04-25 21:31 UTC, dtec83 commented on capitulo4.md
> +</pre>
no entendí acá

2018-04-25 21:33 UTC, dtec83 commented on capitulo4.md
> +Pasando una cadena en blanco usando `end`, la función `print()` no añadirá un salto de linea al final de la cadena, en lugar de esto añadirá una cadena en blanco. Por esta razón ' -Bien, gracias.' ap
listo

2018-04-25 21:39 UTC, dtec83 commented on capitulo4.md
> +Este capítulo explora las diferentes formas en las que se puede utilizar la función `print()`. Los caracteres de escape se utilizan para los caracteres que son difíciles o imposibles de introducir al
listo

2018-04-25 21:42 UTC, dtec83 commented on capitulo4.md
> +La función `print()` añade automáticamente un carácter de salto de línea al final de la cadena que se pasa para imprimr en pantalla. La mayor parte del tiempo, es un atajo útil. Pero a veces no quier
palabra clave sigue siendo palabra clave, leer comentario arriba y avisas

2018-04-25 21:44 UTC, dtec83 commented on capitulo4.md
> +Al añadir este nivel de control sobre el texto que mostraremos en la pantalla, puedes tener formas más flexibles para hacerlo.
listo, supongo que te referís al último comando

2018-04-25 21:53 UTC, dtec83 reviewed
listo

2018-04-25 21:53 UTC, dtec83 commented on capitulo4.md
> +## Ejemplo de ejecución del programa Chistes
listo

2018-04-25 21:55 UTC, dtec83 commented on capitulo4.md
> +
listo

2018-04-25 21:55 UTC, dtec83 commented on capitulo4.md
> +
listo

2018-04-25 22:03 UTC, dtec83 commented on capitulo4.md
> +
listo

2018-04-25 22:03 UTC, dtec83 commented on capitulo4.md
> +Si obtienes errores después de escribir este código, compáralo con el código del libro con la herramienta diff en línea en http://invpy.com/es/diff/chistes.
listo

2018-04-25 22:03 UTC, dtec83 commented on capitulo4.md
> +</pre>
listo

2018-04-25 22:07 UTC, dtec83 commented on capitulo4.md
> +<b>chistes.py</b>
está usando el chistes.py de la traducción de español que me pasaste, que tiene un nuevo set de bromas (la traducción de inglés a español de las existentes no tienen sentido en español)

2018-04-25 22:07 UTC, dtec83 commented on capitulo4.md
> +<b>chistes.py</b>
me avisas si lo dejamos con chistes.py (Es otro file distinto, no el mismo jokes.py)

2018-04-25 22:20 UTC, dtec83 commented on capitulo4.md
> +<pre>
listo

2018-04-25 22:22 UTC, dtec83 commented on capitulo4.md
> +Las líneas de la 1 a la 3 tienen llamadas a la función `print()` que se utiliza para preguntar y responder al chiste. No se quiere que la jugadora lea de inmediato la respuesta del chiste, por lo que
listo

2018-04-25 22:23 UTC, dtec83 commented on capitulo4.md
> +La persona usuaria podría escribir una cadena y pulsar INTRO, pero esa cadena no estará siendo almacenada en ninguna variable. El programa tan solo la olvidará y se moverá a la siguiente línea de cód
listo

2018-04-25 22:24 UTC, dtec83 commented on capitulo4.md
> +La última llamada a la función `print()` no tiene argumento de cadena. Esto le indica al programa que solamente despliegue una línea en blanco. Las líneas en blanco pueden ser útiles para evitar que
listo

2018-04-25 22:24 UTC, dtec83 commented on capitulo4.md
> +<pre>
em?

2018-04-25 22:24 UTC, dtec83 commented on capitulo4.md
> +<pre>
nada aquí?

2018-04-25 22:25 UTC, dtec83 commented on capitulo4.md
> +</pre>
??

2018-04-25 22:25 UTC, dtec83 commented on capitulo4.md
> +
??

2018-04-25 22:28 UTC, dtec83 commented on capitulo4.md
> +En la línea 5 hay una barra invertida justo antes de la comilla simple (note que es una barra invertida y no una barra inclinada). Esta barra invertida indica que la letra que se encuentra justo desp
listo

2018-04-25 22:29 UTC, dtec83 commented on capitulo4.md
> +En este caso el caracter de escape es un signo de pregunta. Si este caso, si no se incluía la barra invertida, en `¿Porqué` el signo de pregunta hubiera sido mal interpretado y habría generado un err
listo

2018-04-25 22:31 UTC, elopio commented on capitulo4.md
> +</pre>
Con tres asteriscos aparece una línea horizontal. Y entonces queda con el mismo formato del original, el código entre dos líneas horizontales.

2018-04-25 22:34 UTC, dtec83 commented on capitulo4.md
> +Ahora, ¿cómo se podría imprimir una barra invertida?. Si se ejecuta la siguiente línea de código desde una terminal, no funcionaría:
listo

2018-04-25 22:34 UTC, dtec83 commented on capitulo4.md
> +<pre>
***? listo

2018-04-25 22:34 UTC, elopio commented on capitulo4.md
> +* Utilizando el argumento palabra clave "end" de la función print() para evitar nuevas lineas
Tomé la traducción de aquí: https://en.wikipedia.org/wiki/Named_parameter
A mi argumento palabra clave me parece dificil de leer y nada claro, son tres sustantivos seguidos.

2018-04-25 22:36 UTC, elopio commented on capitulo4.md
> +<b>chistes.py</b>
no se, yo ya no se. Dejemoslo así y luego discutimos con cervezas.

2018-04-25 22:36 UTC, elopio commented on capitulo4.md
> +<pre>
que faltan los tres asteriscos para delimitar el código.

2018-04-25 22:36 UTC, elopio commented on capitulo4.md
> +
que faltan los tres asteriscos para delimitar el código.

2018-04-25 22:36 UTC, dtec83 commented on capitulo4.md
> +>>> print('Él se fue volando en un helicóptero verde\turquesa.')
listo

2018-04-25 22:37 UTC, elopio commented on capitulo4.md
> +<pre>
sí :)

2018-04-25 22:37 UTC, elopio commented on capitulo4.md
> +<pre>
que faltan los tres asteriscos para delimitar el código.

2018-04-25 22:37 UTC, dtec83 commented on capitulo4.md
> +Él se fue volando en un helicóptero verde    urquesa.
listo

2018-04-25 22:37 UTC, elopio commented on capitulo4.md
> +</pre>
que faltan los tres asteriscos para delimitar el código.

2018-04-25 22:37 UTC, dtec83 commented on capitulo4.md
> +</pre>
??

2018-04-25 22:40 UTC, dtec83 commented on capitulo4.md
> +Esto es porque la "t" en "turquesa" fue vista como un **caracter de escape** debido a que estaba después de una barra invertida. El caracter de escape `t` simula la pulsación de la tecla TAB de tu te
listo

2018-04-25 22:40 UTC, dtec83 commented on capitulo4.md
> +En lugar de eso, prueba con esta línea:
listo

2018-04-25 22:40 UTC, dtec83 commented on capitulo4.md
> +<pre>
listo

2018-04-25 22:40 UTC, dtec83 commented on capitulo4.md
> +>>> print('Él se fue volando en un helicóptero verde\\turquesa.')
listo

2018-04-25 22:41 UTC, dtec83 commented on capitulo4.md
> +De esta manera el `\\` es un caracter de barra invertida en lugar de un `\t` que es interpretado por Python como un TAB.
listo

2018-04-25 22:43 UTC, dtec83 commented on capitulo4.md
> +La tabla **4-1** podremos encontrar una lista de caracteres de escape en Python.
listo

2018-04-25 22:43 UTC, dtec83 commented on capitulo4.md
> +|Caracter de Escape | Lo Que Imprime |
listo

2018-04-25 22:43 UTC, dtec83 commented on capitulo4.md
> +| `\n`     | Salto de línea       |
listo

2018-04-25 22:44 UTC, dtec83 commented on capitulo4.md
> +Mientras todavía estamos en una terminal interactiva, veamos un poco más a fondo a las comillas. Las cadenas no siempre tienen que estar entre comillas simples en Python. También se pueden poner entr
listo

2018-04-25 22:44 UTC, dtec83 commented on capitulo4.md
> +<pre>
listo

2018-04-25 22:46 UTC, dtec83 commented on capitulo4.md
> +>>> print('Hola Mundo')
listo

2018-04-25 22:46 UTC, dtec83 commented on capitulo4.md
> +>>> print("Hola Mundo")
listo

2018-04-25 22:46 UTC, dtec83 commented on capitulo4.md
> +</pre>
listo

2018-04-25 22:46 UTC, dtec83 commented on capitulo4.md
> +Pero no se pueden mezclar las comillas simples con las dobles. Esta siguiente línea va a retornar un error porque utiliza ambas comillas al mismo tiempo:
listo

2018-04-25 22:46 UTC, dtec83 commented on capitulo4.md
> +<pre>
listo

2018-04-25 22:47 UTC, dtec83 commented on capitulo4.md
> +>>> print('Hola mundo")
listo

2018-04-25 22:47 UTC, dtec83 commented on capitulo4.md
> +</pre>
listo

2018-04-25 22:47 UTC, dtec83 commented on capitulo4.md
> +Personalmente prefiero utilizar comillas simples para no tener que mantener presionada la tecla SHIFT para escribirlas. Son mucho más fáciles de escribir y a Python no le importa cuál de las dos util
listo

2018-04-25 23:13 UTC, dtec83 commented on capitulo4.md
> +Tenga en cuenta que al igual que necesita la barra invertida (`\'`), para tener una comilla simple en una cadena encerrada entre comillas simples, también va a necesitar la barra invertida (`\"`) par
listo

2018-04-25 23:13 UTC, dtec83 commented on capitulo4.md
> +<pre>
listo

2018-04-25 23:14 UTC, dtec83 commented on capitulo4.md
> +>>> print('Le pedí prestado el carro a Pedro pa\'ir al pueblo. Él dijo, "Seguro."')
listo

2018-04-25 23:14 UTC, dtec83 commented on capitulo4.md
> +En las cadenas de comillas simples no necesitas escapar las comillas dobles, y en las cadenas de comillas dobles no necesitas escapar las comillas simples. El intérprete de Python tiene inteligencia
arreglado

2018-04-25 23:14 UTC, dtec83 commented on capitulo4.md
> +>>> print("Él dijo, \"No puedo creer que lo dejaste llevarse el carro pa'l pueblo\"")
listo

2018-04-25 23:15 UTC, dtec83 commented on capitulo4.md
> +## El parámetro de palabra clave `end` de la función print()
listo, lo de palabra clave pendiente, leer el primer comentario y me avisas

2018-04-25 23:15 UTC, dtec83 commented on capitulo4.md
> +Ahora regresemos al archivo chistes.py y observemos las líneas de la 9 a las 6:
listo

2018-04-25 23:15 UTC, dtec83 commented on capitulo4.md
> +<pre>
listo

2018-04-25 23:18 UTC, dtec83 commented on capitulo4.md
> +Recordemos que un argumento es un valor que se le pasa a una llamada de función. La cadena en blanco qus se le pasa a la función `print()` se llama **argumento** de palabra clave. El `end` que se enc
listo, menos lo de palabra clave, avisas de eso luego de leer el primer comentario al respecto

2018-04-25 23:18 UTC, dtec83 commented on capitulo4.md
> +<pre>
listo

2018-04-25 23:18 UTC, dtec83 commented on capitulo4.md
> +</pre>
listo

2018-04-25 23:30 UTC, dtec83 commented on capitulo4.md
> +
listo

2018-04-26 04:33 UTC, come-maiz approved these changes

2018-04-26 04:35 UTC, merged

2018-04-26 04:35 UTC, elopio commented
:grinning: