Capitulo2
JaquerEspeis/inventar-con-python pull request #6
Opened 2018-03-20 06:35 UTC by kanguarrovi

Aquí está la traducción del Capítulo 2. 
Perdón que me demorara tanto.

Cualquier cambio para ajustarlo a la convención del libro será recibido de buena manera.

2018-04-07 18:38 UTC, elopio commented
Uy, buenísimo. Perdón por no haberlo revisado antes, no lo había visto. Lo haré apenas pueda.

¿Usted está en el chat del JaquerEspeis? Ahí me puede escribir si pasa mucho tiempo sin que revise los PR, como con este.

2018-04-14 17:32 UTC, kanguarrovi commented
Tranquilo. Más bien yo no he continuado con las traducciones por estar centrándome en desarrollo.

Vieras que no, no estoy en el chat de JaquerEspeis. Desconozco completamente la comunidad.

2018-04-18 03:44 UTC, elopio commented on capitulo2.md
> +le muestran texto al usuario, y los usuarios le introducen texto a los
cómo política del jáquerespeis, estamos usando más femeninos que masculinos en nuestras traducciones.
Porfa cambie `a la usuaria` y `las usuarias`.

2018-04-18 04:53 UTC, come-maiz requested changes

2018-04-18 04:53 UTC, come-maiz commented on capitulo2.md
> +programas a través del teclado. En este capítulo, harás tu primer programa,
La traducción inicial siempre debería ser en español neutro, entonces en lugar de tratar a la usuaria de «tu», que es específico de algunas regiones, debemos tratarla de «usted». Así, luego es más fácil ajustar la traducción a español de Costa Rica y usar voseo, o a otras regiones.

Entonces, en lugar de «harás tu», «hará su».

2018-04-18 04:53 UTC, come-maiz commented on capitulo2.md
> +el cual hace ambas cosas. Aprenderás a guardar texto en variables, combinar
Aprenderá

2018-04-18 04:53 UTC, come-maiz commented on capitulo2.md
> +texto, y mostrar el texto en la pantalla. El programa que crearás muestra el
creará

2018-04-18 04:53 UTC, come-maiz commented on capitulo2.md
> +saludo *Hello world* y pregunta por el nombre del usuario.
de la usuaria.

2018-04-18 04:53 UTC, come-maiz commented on capitulo2.md
> +* String (hileras)
En lugar de hileras, `cadenas de caracteres`.

2018-04-18 04:53 UTC, come-maiz commented on capitulo2.md
> +* String (hileras)
En lugar de String, Strings

2018-04-18 04:53 UTC, come-maiz commented on capitulo2.md
> +* Concatenación de strings
de cadenas de caracteres

2018-04-18 04:53 UTC, come-maiz commented on capitulo2.md
> +* Tipos de datos (como strings o enteros)
cadenas de caracteres

2018-04-18 04:53 UTC, come-maiz commented on capitulo2.md
> +saludo *Hello world* y pregunta por el nombre del usuario.
En lugar de *Hello world* (con cursiva, *), `Hello world` (como texto con ancho fijo, `)

2018-04-18 04:53 UTC, come-maiz commented on capitulo2.md
> +* La función *print()*
`print()`, con backtick, no con asteriscos.

2018-04-18 04:53 UTC, come-maiz commented on capitulo2.md
> +* La función *input()*
`input()`

2018-04-18 04:53 UTC, come-maiz commented on capitulo2.md
> +* Sensibilidad de caso
Yo aquí pondría algo así como: Diferencia entre mayúsculas y minúsculas.

2018-04-18 04:53 UTC, come-maiz commented on capitulo2.md
> +## Valores *string*
Valores de cadenas de caracters

2018-04-18 04:53 UTC, come-maiz commented on capitulo2.md
> +En Python, los valores de texto son llamados *strings* (hileras en inglés).
*strings* (cadenas de caracteres, en inglés).

2018-04-18 04:53 UTC, come-maiz commented on capitulo2.md
> +Los strings pueden ser usadas como valores enteros o flotantes. Usted puede
Los valores de cadenas de caracteres pueden igual que como se usan valores enteros o valores flotantes.

2018-04-18 04:53 UTC, come-maiz commented on capitulo2.md
> +el cual hace ambas cosas. Aprenderás a guardar texto en variables, combinar
Me gusta más «almacenar» que «guardar».

2018-04-18 04:53 UTC, come-maiz commented on capitulo2.md
> +guardar strings en variables. En el código, los strings empiezan y terminan
almacenar cadenas de caracteres.

2018-04-18 04:53 UTC, come-maiz commented on capitulo2.md
> +guardar strings en variables. En el código, los strings empiezan y terminan
las cadenas de caracteres empiezan ...

2018-04-18 04:53 UTC, come-maiz commented on capitulo2.md
> +con comillas simples (''). Ingresa este códido en la consola interactiva:
En lugar de «Ingresa», «Escriba»

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +con comillas simples (''). Ingresa este códido en la consola interactiva:
Me gusta consola interactiva. Yo estaba usando «shell» interactivo, voy a cambiarlo en lo que ya tenemos, reporté #7 para arreglarlo.

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +Las comillas simples le indican a Python donde el string comienza y donde
dónde comienza y dónde termina la cadena de caracteres.

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +termina. Estas comillas no son parte del valor del texto del string. Ahora
de la cadena de caracteres.

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +si ingresas *spam* dentro de la consola interactiva, podrás ver el contenido
si escribe `spam` (backtick en lugar de *)

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +si ingresas *spam* dentro de la consola interactiva, podrás ver el contenido
en lugar de «podrás ver», «verá»

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +de la variable *spam*. Recuerda, Python evalua las variables como el valor
`spam`.

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +de la variable *spam*. Recuerda, Python evalua las variables como el valor
Recuerde

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +guardado dentro de la variable. En este caso, este es el string *hello*.
almacenado

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +guardado dentro de la variable. En este caso, este es el string *hello*.
la cadena de caracteres `'hola'`.

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +Los strings pueden tener cuaquier caracter que posea el teclado dentro de
Las cadenas de caracteres

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +ellos y pueden ser tan largos como lo desees. Todos estos son ejemplos de
desee.

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +strings:
cadenas de caracteres.

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +>>> <b>spam = 'hello'</b>
yo creo que deberíamos traducir 'hello' a 'hola'

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +'hello'
hola

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +'Hi there!'
Tal vez, ¡buenos días!

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +'KITTENS'
GATITOS

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +'7 apples, 14 oranges, 3 lemons'
7 manzanas, 14 naranjas, 3 limones.

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +'Anything not pertaining to elephants is irrelephant.'
Cualquier cosa no relacionada con elefantes es irrelefante.
:man_facepalming:

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +'A long time ago, in a galaxy far, far away...'
Hace mucho tiempo, en una galaxia muy, muy lejana ...

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +## Concatenación de strings
cadenas de caracteres

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +Usted puede combinar strings con operadores para crear expresiones, igual
cadenas de caracteres

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +que como lo había hecho con los *ints* y *floats*. Cuando combinas dos
con los valores entereros y flotantes

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +que como lo había hecho con los *ints* y *floats*. Cuando combinas dos
combina

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +strings con el operador de adición: '+', esa acción es llamada concatenación
cadenas de caracteres

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +strings con el operador de adición: '+', esa acción es llamada concatenación
En lugar de «el operador de adición '+'», «el operador `+`»

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +de strings. Ejecuta 'Hello' + 'World!' en la consola interactiva:
cadenas de caracteres

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +de strings. Ejecuta 'Hello' + 'World!' en la consola interactiva:
`'Hola' + 'Mundo!'`

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +'HelloWorld!'
HolaMundo!

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +La expresión es evaluada como un único valor de tipo string: 'HelloWorld!'.
es evaluada a un único valor de cadena de caracteres.

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +strings condatendos, a diferencia de este ejemplo:
las cadenas de caracteres concatenadas.

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +'Hello World!'
Hola Mundo!

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +El operador de adición ('+'), trabaja distinto con los valores de strings y
El operador `+`

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +El operador de adición ('+'), trabaja distinto con los valores de strings y
cadenas de caracteres

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +los enteros porque son *tipos de datos* distintos. Todos los valores pretenecen
Todos los valores tienen un tipo de datos.

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +valor 5 es un entero (int). El tipo de dato le dice a Python qué debe realizar
yo borraría el «(int)», no está en el original.

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +el operador cuando exalúa expresiones. El operador de adición concatena strings,
evalúa

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +el operador cuando exalúa expresiones. El operador de adición concatena strings,
El operador `+`

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +el operador cuando exalúa expresiones. El operador de adición concatena strings,
cadenas de caracteres

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +## Escribiendo programas en el editor de archivos de IDLE
editor de archivos IDLE

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +Hasta el momento, has estado escribiendo instrucciones dentro de la consola
ha

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +interaractiva, una por una. Cuando escribes programas, ingresas varias
escribe

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +interaractiva, una por una. Cuando escribes programas, ingresas varias
ingresa

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +intrucciones y son ejecutadas inmediatamente, y eso es lo que harás a
hará

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +intrucciones y son ejecutadas inmediatamente, y eso es lo que harás a
en lugar de «son ejecutadas inmediatamente», «todas son ejecutadas a la vez».

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +continuación.¡Es hora de escribir tu primer programa!
su

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +Además del intérprete, el IDLE tiene otra parte llamada *file editor*
yo borraría «el»

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +Además del intérprete, el IDLE tiene otra parte llamada *file editor*
Y borraría file editor, dejaría solo editor de archivos.

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +(editor de archivos). Para abrirlo, has click en la parte de *File* (Archivo)
haga clic

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +(editor de archivos). Para abrirlo, has click en la parte de *File* (Archivo)
Igual, sin File, solo Archivo

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +del menu localizado en el pánel superior de la consola interactiva. Luego
en lugar de «en el panel», «en la parte superior»

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +selecciona *New file* (nuevo archivo). Una ventana en blanco aparecerá para
Sin New file

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +que escribar el código del programa dentro de ella, como se muestra en la
escriba

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +que escribar el código del programa dentro de ella, como se muestra en la
en lugar de «ella», «esta»

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +Ambas ventanas parecen similares, pero recuerda: la consola interactiva tiene el
recuerde

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +prompt >>>, mientras que el editor de archivos no lo posee.
«prompt», como es en inglés, hay que ponerle comillas.

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +prompt >>>, mientras que el editor de archivos no lo posee.
en lugar de «no lo posee», solo «no»

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +## Creando el programa *Hello World!*
Hola Mundo, y sin cursiva.

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +Es una tradicción para los programadores que el primer programa que realicen
las programadoras

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +muestre *Hello world!* en la pantalla. Ahora mismo crearás tu primer programa
`Hola Mundo`

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +muestre *Hello world!* en la pantalla. Ahora mismo crearás tu primer programa
creará su

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +*Hello World!*.
Hola Mundo, sin cursiva

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +Cuando escribas tu programa, recuerda no incluir los numberos al principio de
escriba su

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +Cuando escribas tu programa, recuerda no incluir los numberos al principio de
recuerde

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +Cuando escribas tu programa, recuerda no incluir los numberos al principio de
números

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +del editor de archivos te indicará donde se encuentra el cursor, de esta manera
le

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +podrás verificar en cual línea de código te encuentras. La figura 2-2 muestra
podrá

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +podrás verificar en cual línea de código te encuentras. La figura 2-2 muestra
se encuentra

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +Figura 2-2: La esquina inferior derecha del editor de archivos te dice donde
le

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +Ingresa el siguiente texto dentro de la nueva ventana del editor de archivos.
Escriba

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +1. # This program says hello and asks for my name.
Este programa dice hola y pregunta por mi nombre.

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +2. print('Hello world!')
print('Hola mundo!')

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +3. print('What is your name?')
¿Cuál es su nombre?

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +5. print('It is good to meet you, ' + myName)
Gusto en conocerle,

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +hayas escrito el código, la ventana deberá verse como la Figura 2-3.
haya

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +Figura 2-3: el editor de archivos se verá como esto cuando hayas escrito el código.
haya

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +Verifica si tu ventana de IDLE se ve parecida.
Verifique

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +## Guardando tu programa
su

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +Cuando hayas entrado a tu código fuente, guárdalo haciendo click en
haya escrito su código...

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +Cuando hayas entrado a tu código fuente, guárdalo haciendo click en
guárdelo

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +Cuando hayas entrado a tu código fuente, guárdalo haciendo click en
clic

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +File -> Save As. (Archivo -> Guardar como). O presionando Ctrl + S para
Sin File -> Save As

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +área de texto y luego has click en Save (Guardar).
haga clic en **Guardar**

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +Figura 2-4: Guardando tu programa.
su

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +Recurrentemente deberías guardar tus programas mientras los escribes.
Debería guardar sus programas con frecuencia mientras los escribe.

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +De esa manera, si el ordenador falla o te sales accidentalmente del IDLE,
En lugar de «el ordenador», «la computadora»

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +De esa manera, si el ordenador falla o te sales accidentalmente del IDLE,
se sale

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +no perderás mucho trabajo que hayas realizado.
perderá

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +no perderás mucho trabajo que hayas realizado.
Ese «que hayas realizado» no está en el orginal. Mejor borrarlo.

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +Para cargar tu programa previamente guardado, has click en File -> Open
su

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +Para cargar tu programa previamente guardado, has click en File -> Open
haga clic

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +Para cargar tu programa previamente guardado, has click en File -> Open
Sin File -> Open

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +(Archivo -> Abrir). Selecciona el archivo *hello.py* en la ventana que
Seleccione

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +aparece y has click sobre el botón Open (Abrir). Tu programa *hello.py*
haga clic

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +aparece y has click sobre el botón Open (Abrir). Tu programa *hello.py*
Sin Open

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +aparece y has click sobre el botón Open (Abrir). Tu programa *hello.py*
Su

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +## Ejecutando tu programa
su

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +Es hora de ejecutar el programa. Has click en Run->Run Module. O sólo presiona F5 desde el editor de archivos (FN-5 en Mac). Tu programa será
Haga clic

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +Es hora de ejecutar el programa. Has click en Run->Run Module. O sólo presiona F5 desde el editor de archivos (FN-5 en Mac). Tu programa será
Ejecutar -> Ejecutar Módulo

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +Es hora de ejecutar el programa. Has click en Run->Run Module. O sólo presiona F5 desde el editor de archivos (FN-5 en Mac). Tu programa será
presione

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +Es hora de ejecutar el programa. Has click en Run->Run Module. O sólo presiona F5 desde el editor de archivos (FN-5 en Mac). Tu programa será
En lugar de Mac, OS X

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +Es hora de ejecutar el programa. Has click en Run->Run Module. O sólo presiona F5 desde el editor de archivos (FN-5 en Mac). Tu programa será
Su programa

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +Ingresa tu nombre cuando el programa te lo solicite. Se parecerá como
Escriba su nombre cuando el programa se lo solicite

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +Ingresa tu nombre cuando el programa te lo solicite. Se parecerá como
Se parecerá a

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +Cuando ingresas tu nombre y presionas ENTER, el programa te saludará por
escriba su nombre y presiona

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +Cuando ingresas tu nombre y presionas ENTER, el programa te saludará por
le saludará

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +tu nombre. ¡Felicidades! Has escrito tu primer programa y ahora eres un(a)
su nombre

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +tu nombre. ¡Felicidades! Has escrito tu primer programa y ahora eres un(a)
Ha escrito

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +tu nombre. ¡Felicidades! Has escrito tu primer programa y ahora eres un(a)
ahora es una

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +programador(a). Presiona F5 de nuevo para ejecutar el programa una segunda
programadora

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +programador(a). Presiona F5 de nuevo para ejecutar el programa una segunda
Presione

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +vez e ingresar un nombre distinto.
y escriba

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +Si tienes algún error, compara tu código con el código de este libro en
tiene, compare

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +(En idioma inglés) Copia y pega tu código desde el editor de archivos a
Copie y pegue su

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +la página web y haz click en el botón que dice <b>Compare</b>. Esta
haga clic

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +herramienta destacará cualquier diferencia que haya entre tu código y
su

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +Mientras programas, si tienes un <b>NameError</b> que se ve como el de
programa, tiene

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +a continuación, eso significa que estás utilizando Python2 en lugar de
está

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +Hello world!
¡Hola mundo!

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +What is your name?
¿Cuál es su nombre?

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +Para solucionar este problema, install Python3.4 y vuelve a ejecutar el
instale, vuelva

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +programa. (Ve a "Descargar e instalar Python" en la página xxv.)
vaya

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +## Como funciona el programa *Hello World*
Hola Mundo, sin cursiva

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +instrucciones crean el programa. Las instrtaciones de un programa de
En lugar de «crean», «forman»

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +instrucciones crean el programa. Las instrtaciones de un programa de
instrtaciones -> instrucciones

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +computadora son como pasos en una receta. Python ejecuta cada
en lugar de «ejecuta», «completa»

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +instruccion en orden, comenzando desde la cima del programa
En lugar de «cima», «parte de arriba»

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +moviendose hasta abajo.
moviéndose

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +se llama la *ejecución*. Cuando un programa comienza, la ejecución is
es

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +## Comentarios para el programador
la programadora

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +La primera línea del programa *Hello World* es un comentario.
Hola Mundo

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +1. # This program says hello and asks for my name.
Traducir

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +no están escritas para Python, sino para ti, el programador. Python ignora
usted, la programadora

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +los comentarios cuando ejecuta un programa. Los programadores usualmente
Las programadoras

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +título a su programa. El comentario en el programa *Hello World* te dice
Hola Mundo le dice

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +que el programa saluda y pregunta por tu nombre.
su

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +Una función es como un miniprograma dentro de tu programa que contiene
su

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +algunas instrucciones para ejecutar en Python. Lo genial acerca de las
para que Python ejecute

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +funciones es que sólo necesitas saber qué es lo que hacen, y no como lo
necesita

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +funciones es que sólo necesitas saber qué es lo que hacen, y no como lo
cómo

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +hacen. Python provee algunas funciones implementadas. Usamos *print()* e
En lugar de provee, brinda

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +hacen. Python provee algunas funciones implementadas. Usamos *print()* e
en lugar de implementadas, incorporadas

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +hacen. Python provee algunas funciones implementadas. Usamos *print()* e
`print()`, con backticks

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +*input()* en el programa *Hello World*.
Hola Mundo

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +Una funcion de *llamada* es una instrucción que le dice a Python que
Una *llamada a función*

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +ejecute el código dentro de una función. Por ejemplo, tu programa llama
su

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +la función *print()* para mostrar un string en la pantalla. La función
`print()`

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +la función *print()* para mostrar un string en la pantalla. La función
una cadena de caracteres

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +*print()* toma el string que escribiste dentro de los paréntesis como
`print()`

2018-04-18 04:53 UTC, elopio commented on capitulo2.md
> +*print()* toma el string que escribiste dentro de los paréntesis como
la cadena de caracteres que escribió

2018-04-18 04:53 UTC, come-maiz commented on capitulo2.md
> +Las líneas 2 y 3 del programa *Hello World* son llamadas a *print()*:
Hola Mundo

2018-04-18 04:53 UTC, come-maiz commented on capitulo2.md
> +3. print('What is your name?')
Traducir

2018-04-18 04:53 UTC, come-maiz commented on capitulo2.md
> +Un valor entre paréntesis en la función es llamado como *argumento*. El
Un valor entre los paréntesis en una llamada a función es un *argumento*.

2018-04-18 04:53 UTC, come-maiz commented on capitulo2.md
> +argumento de la llamada *print()* en la línea 2 is 'Hello world!', y
`print()`

2018-04-18 04:53 UTC, come-maiz commented on capitulo2.md
> +argumento de la llamada *print()* en la línea 2 is 'Hello world!', y
`'¡Hola mundo!'`

2018-04-18 04:53 UTC, come-maiz commented on capitulo2.md
> +el argumento de la llamada *print()* en la línea 3 es 'What's your name?'.
`'¿Cuál es su nombre?'`

2018-04-18 04:53 UTC, come-maiz commented on capitulo2.md
> +Esto es llamado como *pasar* el argumento a la función.
A esto se le llama *pasar*

2018-04-18 04:53 UTC, come-maiz commented on capitulo2.md
> +La línea 4 es una declaración de asignación de una variable, *myName*,
`myName`

2018-04-18 04:53 UTC, come-maiz commented on capitulo2.md
> +y una función de llamada, *input()*:
`input()`

2018-04-18 04:53 UTC, come-maiz commented on capitulo2.md
> +Cuando *input()* es llamada, el programa espera para que el usuario
la usuaria

2018-04-18 04:53 UTC, come-maiz commented on capitulo2.md
> +ingrese un texto. El string de texto que el usuario ingresa se convierte
escriba

2018-04-18 04:53 UTC, come-maiz commented on capitulo2.md
> +ingrese un texto. El string de texto que el usuario ingresa se convierte
El texto de la cadena de caracteres que la usuaria escribe

2018-04-18 04:53 UTC, come-maiz commented on capitulo2.md
> +en el valor que la llamada a función evalúa. Las llamadas a función
en el valor al que evalúa la llamada a función

2018-04-18 04:53 UTC, come-maiz commented on capitulo2.md
> +El valor que la llamada a función se llama valor de retorno (return value).
El valor al que evalúa la llamada a función

2018-04-18 04:53 UTC, come-maiz commented on capitulo2.md
> +El valor que la llamada a función se llama valor de retorno (return value).
Me parece que return value no es necesario

2018-04-18 04:53 UTC, come-maiz commented on capitulo2.md
> +mismo que "el valor que la llamada a función evalúa".) En este caso, el
el valor al que evalúa la llamada a función

2018-04-18 04:53 UTC, come-maiz commented on capitulo2.md
> +valor de retorno de la función *input()* es el string que el usuario
la cadena de caracteres que la usuaria

2018-04-18 04:53 UTC, come-maiz commented on capitulo2.md
> +ingresó: su nombre. Si el usaurio ingresa *Albert*, la llamada
escribió

2018-04-18 04:53 UTC, come-maiz commented on capitulo2.md
> +ingresó: su nombre. Si el usaurio ingresa *Albert*, la llamada
si la usuaria escribe

2018-04-18 04:53 UTC, come-maiz commented on capitulo2.md
> +función *input()* evalúa el string 'Albert'. La evaluación se ve como esto:
la cadena de caracteres

2018-04-18 04:53 UTC, come-maiz commented on capitulo2.md
> +
Falta una oración aqui.

2018-04-18 04:53 UTC, come-maiz commented on capitulo2.md
> +La última línea de código en el programa *Hello World* es otra llamada a
Hola Mundo

2018-04-18 04:53 UTC, come-maiz commented on capitulo2.md
> +la función *print()*:
`print()`

2018-04-18 04:53 UTC, come-maiz commented on capitulo2.md
> +5. print('It is good to meet you, ' + myName)
traducir

2018-04-18 04:53 UTC, come-maiz commented on capitulo2.md
> +La expresión *'It is good to meet you', + myName* está rodeada por los
traducir

2018-04-18 04:53 UTC, come-maiz commented on capitulo2.md
> +Así es como el programa saluda al usuario por su nombre.
a la usuaria

2018-04-18 04:53 UTC, come-maiz commented on capitulo2.md
> +Una vez el programa executa la última línea, *termina* o *sale*. Esto
Una vez que el programa...

2018-04-18 04:53 UTC, come-maiz commented on capitulo2.md
> +valores de las variables, incluído el string guardado en *myName*. Si
incluida la cadena de caracteres

2018-04-18 04:53 UTC, come-maiz commented on capitulo2.md
> +ejecutas el programa otra vez e ingrasas un nombre diferente, el
ejecuta

2018-04-18 04:53 UTC, come-maiz commented on capitulo2.md
> +ejecutas el programa otra vez e ingrasas un nombre diferente, el
escribe

2018-04-18 04:53 UTC, come-maiz commented on capitulo2.md
> +programa pensará que es tu nombre:
su

2018-04-18 04:53 UTC, come-maiz commented on capitulo2.md
> +</pre>
Traducir

2018-04-18 04:53 UTC, come-maiz commented on capitulo2.md
> +Recuerda, la computadora hace exactamente lo que la programaste para hacer.
Recuerde

2018-04-18 04:53 UTC, come-maiz commented on capitulo2.md
> +Recuerda, la computadora hace exactamente lo que la programaste para hacer.
programó

2018-04-18 04:53 UTC, come-maiz commented on capitulo2.md
> +Las computadoras son tontas y sólo siguen las instrucciones que les diste
les dió

2018-04-18 04:53 UTC, come-maiz commented on capitulo2.md
> +de forma exacta. La computadora no le importa si le ingresas tu nombre, o
A la computadora

2018-04-18 04:53 UTC, come-maiz commented on capitulo2.md
> +de forma exacta. La computadora no le importa si le ingresas tu nombre, o
escribe su

2018-04-18 04:53 UTC, come-maiz commented on capitulo2.md
> +el nombre de otra persona o algo sin sentido. Escribe e ingresa lo que quieras. La computadora lo tratará de la misma manera:
o algo tonto

2018-04-18 04:53 UTC, come-maiz commented on capitulo2.md
> +el nombre de otra persona o algo sin sentido. Escribe e ingresa lo que quieras. La computadora lo tratará de la misma manera:
En lugar de «Escribe e ingresa lo que quieras», «Escriba cualquier cosa que quiera»

2018-04-18 04:53 UTC, come-maiz commented on capitulo2.md
> +</pre>
Traducir.
¿De dónde salió shoe? Yo pondría `caca`.

2018-04-18 04:53 UTC, come-maiz commented on capitulo2.md
> +Dar a las variables un nombre descriptivo hace más fácil entender los que
entender lo que

2018-04-18 04:53 UTC, come-maiz commented on capitulo2.md
> +*abrahamLincoln* or *nAmE*, y Python habría ejecutado el programa de la
or -> o

2018-04-18 04:53 UTC, come-maiz commented on capitulo2.md
> +misma manera. Pero estos nombres realmente no nos dicen mucho acerca lo
acerca de

2018-04-18 04:53 UTC, come-maiz commented on capitulo2.md
> +si usted se estuviera mudando a una nueva casa y etiquetas todas las cajas
etiqueta

2018-04-18 04:53 UTC, come-maiz commented on capitulo2.md
> +interactiva que se muestran en este libro usa nombres como *spam*, *eggs*,
usan

2018-04-18 04:53 UTC, come-maiz commented on capitulo2.md
> +descriptivos, y así deben estar en tus programas.
sus

2018-04-18 04:53 UTC, come-maiz commented on capitulo2.md
> +desornadamente las mayúsculas con las minúsculas en tu programa. En lugar
desordenadamente

2018-04-18 04:53 UTC, come-maiz commented on capitulo2.md
> +desornadamente las mayúsculas con las minúsculas en tu programa. En lugar
su

2018-04-18 04:53 UTC, come-maiz commented on capitulo2.md
> +de eso utiliza nombres descriptivos para tus variables.
use

2018-04-18 04:53 UTC, come-maiz commented on capitulo2.md
> +de eso utiliza nombres descriptivos para tus variables.
sus

2018-04-18 04:53 UTC, come-maiz commented on capitulo2.md
> +Los programadores también prefieren usar nombres de variables más cortos
Las programadoras

2018-04-18 04:53 UTC, come-maiz commented on capitulo2.md
> +Una vez que entiendas como usar strings y funciones, ya puedes comenzar
entienda

2018-04-18 04:53 UTC, come-maiz commented on capitulo2.md
> +Una vez que entiendas como usar strings y funciones, ya puedes comenzar
cadenas de caracteres

2018-04-18 04:53 UTC, come-maiz commented on capitulo2.md
> +Una vez que entiendas como usar strings y funciones, ya puedes comenzar
puede

2018-04-18 04:53 UTC, come-maiz commented on capitulo2.md
> +a hacer programas que interactúen con los usuarios. Esto es importante
las usuarias

2018-04-18 04:53 UTC, come-maiz commented on capitulo2.md
> +y el usuario. El usuario ingresa texto a través del teclado con la
la usuaria x2

2018-04-18 04:53 UTC, come-maiz commented on capitulo2.md
> +y el usuario. El usuario ingresa texto a través del teclado con la
escribe

2018-04-18 04:53 UTC, come-maiz commented on capitulo2.md
> +Los strings son sólo valores de un nuevo tipo de datos. Todos los valores
Las cadenas de caracteres

2018-04-18 04:53 UTC, come-maiz commented on capitulo2.md
> +(+) funciona.
cómo el operador `+` funciona

2018-04-18 04:53 UTC, come-maiz commented on capitulo2.md
> +aprenderás más adelante en este libro. Las llamadas a funciones pueden ser
aprenderá

2018-04-18 04:53 UTC, come-maiz commented on capitulo2.md
> +La instrucción o paso en tu programa donde Python está trabajando en un
su

2018-04-18 04:53 UTC, come-maiz commented on capitulo2.md
> +instante dado se llama ejecución. El el Capítulo 3, aprenderás más acerca
aprenderá

2018-04-18 04:53 UTC, come-maiz commented on capitulo2.md
> +listo(a) para hacer programas.
Una vez que aprenda esto, ¡estará lista para crear juegos!

2018-06-07 02:14 UTC, kanguarrovi commented on capitulo2.md
> +</pre>
La idea era ser políticamente correcto. ¡Entonces pondré `caca`!

2018-06-07 02:58 UTC, kanguarrovi commented
Casi 200 correcciones. ¡Hecho!

2018-06-09 17:53 UTC, elopio commented on capitulo2.md
> +En Python, los valores de cadenas de caracteres. Las cadenas de caracteres
En Python, los valores de texto se llaman cadenas de caracteres.

2018-06-09 18:10 UTC, come-maiz requested changes
Gracias @kanguarrovi.
Dejé unas cuantas sugerencias más.

pura vida

2018-06-09 18:10 UTC, come-maiz commented on capitulo2.md
> +Escriba es siguiente códido en la consola interactiva:
Escriba el siguiente código

2018-06-09 18:10 UTC, come-maiz commented on capitulo2.md
> +de la cadena de caracteres. Ahora si ingresas spam dentro de la consola
«escribe» en lugar de «ingresas».

2018-06-09 18:10 UTC, come-maiz commented on capitulo2.md
> +interactiva, verá el contenido de la variable spam. Recuerda, Python evalua
Recuerde, en lugar de Recuerda

2018-06-09 18:10 UTC, come-maiz commented on capitulo2.md
> +las variables como el valor almacanado dentro de la variable. En este caso,
almacenado

2018-06-09 18:10 UTC, come-maiz commented on capitulo2.md
> +Las cadenas de caracteres pueden tener cuaquier caracter que posea el teclado
cualquier

2018-06-09 18:10 UTC, come-maiz commented on capitulo2.md
> +dos cadenas de caracteres con el el operador `+`, esa acción es llamada concatenación
dice: con **el el** operador.
Quitar un **el**.

2018-06-09 18:10 UTC, come-maiz commented on capitulo2.md
> +de cadenas de caracteres. Ejecuta 'Hola' + 'mundo' en la consola interactiva:
Ejecute

2018-06-09 18:10 UTC, come-maiz commented on capitulo2.md
> +La expresión es evaluada como un único valor de cadena de caracteres: 'HelloWorld!'.
El ejemplo está en español y la explicación en inglés.

2018-06-09 18:10 UTC, come-maiz commented on capitulo2.md
> +cadenas de caracteres condatenadas, a diferencia de este ejemplo:
concatenadas

2018-06-09 18:10 UTC, come-maiz commented on capitulo2.md
> +3. print('¿Cuál es tu nombre?')
su en lugar de tu

2018-06-09 18:10 UTC, come-maiz commented on capitulo2.md
> +área de texto y luego haga click en **Guardar** .
clic en lugar de click

2018-06-09 18:10 UTC, elopio commented on capitulo2.md
> +el botón Abrir. Su programa *hello.py* se abrirá en el editor de archivos.
arriba dice hola.py, aquí dice hello.py

2018-06-09 18:10 UTC, elopio commented on capitulo2.md
> +Es hora de ejecutar el programa. Haga click en Ejecutar -> Ejecutar Módulo.
clic

2018-06-09 18:10 UTC, elopio commented on capitulo2.md
> +Cuando escriba su nombre y presiona ENTER, el programa la saludará por
presione

2018-06-09 18:10 UTC, elopio commented on capitulo2.md
> +instrucciones forma el programa. Las instrucciones de un programa de
forman

2018-06-09 18:10 UTC, elopio commented on capitulo2.md
> +La función `print()` toma la cadena de carcateres que escribió dentro de
caracteres

2018-06-09 18:10 UTC, elopio commented on capitulo2.md
> +La línea 4 es una declaración de asignación de una variable, *miNombre*,
myName

2018-06-09 18:10 UTC, elopio commented on capitulo2.md
> +4. miNombre = input()
myName

2018-06-09 18:10 UTC, elopio commented on capitulo2.md
> +mismo que "el valor al que evalúa la llamada a función evalúa".) En este caso, el
quitar el segundo "evalúa"

2018-06-09 18:10 UTC, elopio commented on capitulo2.md
> +escribió: su nombre. Si la usuaria ingresa *Albert*, la llamada función `input()`
la llamada a función

2018-06-09 18:10 UTC, elopio commented on capitulo2.md
> +Si myValue contiene el valor 'Albert', la evaluación se verá así:
myName

2018-06-09 18:10 UTC, elopio commented on capitulo2.md
> +Las computadoras son tontas y sólo siguen las instrucciones que les diste
dio

2018-06-09 18:10 UTC, elopio commented on capitulo2.md
> +que contiene el valor de la variable. Como se discutió en el Capítulo 1,
qué contiene

2018-06-09 18:10 UTC, elopio commented on capitulo2.md
> +desordenadamente las mayúsculas con las minúsculas en tu programa. En lugar
su programa

2018-06-09 18:10 UTC, elopio commented on capitulo2.md
> +instante dado se llama ejecución. El el Capítulo 3, aprenderá más acerca
En el Capítulo

2018-06-10 05:53 UTC, kanguarrovi commented on capitulo2.md
> +Si myValue contiene el valor 'Albert', la evaluación se verá así:
¿Aquí qué hago?

2018-06-11 01:18 UTC, elopio commented on capitulo2.md
> +Si myValue contiene el valor 'Albert', la evaluación se verá así:
dice myValue y debería ser myName

2018-06-11 05:30 UTC, kanguarrovi commented on capitulo2.md
> +Si myValue contiene el valor 'Albert', la evaluación se verá así:
Listo.

2018-06-12 19:50 UTC, come-maiz approved these changes
:shipit: ¡ Gracias @kanguarrovi !

2018-06-12 19:50 UTC, merged